

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: meridian
      POSTGRES_PASSWORD: meridian_pass
      POSTGRES_DB: meridian_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U meridian -d meridian_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.1.11
    command:
      - redpanda
      - start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - "9092:9092"
      - "8082:8082"
      - "9644:9644"
    volumes:
      - redpanda:/var/lib/redpanda/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://meridian:meridian_pass@postgres:5432/meridian_db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=redpanda:29092
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      redpanda:
        condition: service_started
    command: ["node", "apps/api/dist/server.js"]

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    ports:
      - "4000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api/v1
    depends_on:
      - api
    command: ["node", "apps/web/server.js"]

volumes:
  pgdata:
  redpanda:
